import React, { useState } from 'react';
import { ListChecks, CheckSquare, Square, Copy, Check, Sparkles } from 'lucide-react';

interface ChecklistGeneratorProps {
  items: Array<{ id: string; text: string; category: string }>;
  documentName: string;
}

export const ChecklistGenerator: React.FC<ChecklistGeneratorProps> = ({
  items = [],
  documentName = 'Document',
}) => {
  const safeItems = Array.isArray(items) ? items : [];
  const [completedMap, setCompletedMap] = useState<{ [id: string]: boolean }>({});
  const [copied, setCopied] = useState(false);

  const toggleItem = (id: string) => {
    setCompletedMap((prev) => ({
      ...prev,
      [id]: !prev[id],
    }));
  };

  const completedCount = safeItems.filter((item) => completedMap[item.id]).length;
  const progressPercent = safeItems.length > 0 ? Math.round((completedCount / safeItems.length) * 100) : 0;

  const handleCopy = () => {
    const formatted = safeItems
      .map(
        (item) =>
          `${completedMap[item.id] ? '[x]' : '[ ]'} ${item.text} (${item.category})`
      )
      .join('\n');

    const textToCopy = `LegalLens Review Checklist for: ${documentName}\n\n${formatted}\n\nGenerated by LegalLens - Understand before you sign.`;
    navigator.clipboard.writeText(textToCopy);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="bg-white rounded-2xl border border-slate-200 shadow-xs p-6 sm:p-8 space-y-6" id="checklist-generator-section">
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <div className="flex items-center gap-2">
            <h2 className="font-serif text-2xl font-bold text-slate-900">Custom Review Checklist</h2>
            <span className="text-xs bg-slate-100 text-slate-700 px-2 py-0.5 rounded-full font-mono">
              {completedCount} of {safeItems.length} Done
            </span>
          </div>
          <p className="text-xs sm:text-sm text-slate-500 mt-1">
            Practical verification steps tailored strictly to the clauses and obligations in this document.
          </p>
        </div>

        <button
          id="copy-checklist-btn"
          onClick={handleCopy}
          className="inline-flex items-center gap-2 text-xs font-medium px-3.5 py-2 rounded-lg bg-slate-900 hover:bg-slate-800 text-white transition-colors self-start sm:self-auto shadow-xs"
        >
          {copied ? (
            <>
              <Check className="w-3.5 h-3.5 text-emerald-400" />
              <span>Copied to Clipboard</span>
            </>
          ) : (
            <>
              <Copy className="w-3.5 h-3.5" />
              <span>Copy Checklist</span>
            </>
          )}
        </button>
      </div>

      {/* Progress Bar */}
      <div className="space-y-1.5">
        <div className="flex justify-between text-xs text-slate-500 font-medium">
          <span>Review Progress</span>
          <span>{progressPercent}% completed</span>
        </div>
        <div className="w-full h-2 bg-slate-100 rounded-full overflow-hidden">
          <div
            className="h-full bg-slate-900 transition-all duration-300 rounded-full"
            style={{ width: `${progressPercent}%` }}
          />
        </div>
      </div>

      {/* Checklist Items */}
      {safeItems.length === 0 ? (
        <div className="p-8 text-center bg-slate-50 rounded-xl border border-slate-200 text-slate-600 text-sm">
          No action checklist items were generated for this document.
        </div>
      ) : (
        <div className="divide-y divide-slate-100 border border-slate-200 rounded-xl overflow-hidden">
          {safeItems.map((item) => {
          const isDone = Boolean(completedMap[item.id]);

          return (
            <div
              key={item.id}
              onClick={() => toggleItem(item.id)}
              className={`p-4 flex items-start gap-3.5 cursor-pointer transition-colors select-none ${
                isDone ? 'bg-slate-50 text-slate-400' : 'bg-white hover:bg-slate-50/70 text-slate-800'
              }`}
            >
              <div className="pt-0.5 text-slate-400 hover:text-slate-600">
                {isDone ? (
                  <CheckSquare className="w-5 h-5 text-emerald-600" />
                ) : (
                  <Square className="w-5 h-5 text-slate-400" />
                )}
              </div>

              <div className="flex-1 space-y-0.5">
                <p
                  className={`text-sm leading-relaxed ${
                    isDone ? 'line-through text-slate-500' : 'font-medium text-slate-900'
                  }`}
                >
                  {item.text}
                </p>
                <span className="inline-block text-[11px] text-slate-400 font-medium">
                  {item.category}
                </span>
              </div>
            </div>
          );
        })}
        </div>
      )}
    </div>
  );
};
